/*
 * defines.h
 *
 * Created: 11/6/2014 11:32:00 AM
 *  Author: kwgilpin
 */ 


#ifndef DEFINES_H_
#define DEFINES_H_


#define I2C_SLAVE_ADDR 0x03

#define I2C_REGISTER_ADDR_LEDS			0x01
#define I2C_REGISTER_ADDR_IR_CARRIER	0x02
#define I2C_REGISTER_ADDR_IR_LEDS		0x03
#define I2C_REGISTER_ADDR_AMBIENT_LIGHT	0x04

#define I2C_REGISTER_ADDR_TX_BUF		0x10
#define I2C_REGISTER_ADDR_TX_COUNT		0x11

#define I2C_REGISTER_ADDR_RX_BUF		0x20
#define I2C_REGISTER_ADDR_RX_COUNT		0x21

#define DDR_LED_RED				DDRA
#define PORT_LED_RED			PORTA
#define PIN_LED_RED				PINA
#define PIN_NUMBER_LED_RED		0

#define DDR_LED_GREEN			DDRA
#define PORT_LED_GREEN			PORTA
#define PIN_LED_GREEN			PINA
#define PIN_NUMBER_LED_GREEN	1

#define DDR_LED_BLUE			DDRA
#define PORT_LED_BLUE			PORTA
#define PIN_LED_BLUE			PINA
#define PIN_NUMBER_LED_BLUE		2

#define DDR_IRLED0_ANODE		DDRA
#define PORT_IRLED0_ANODE		PORTA
#define PIN_IRLED0_ANODE		PINA
#define PIN_NUMBER_IRLED0_ANODE	5

#define DDR_IRLED1_ANODE		DDRA
#define PORT_IRLED1_ANODE		PORTA
#define PIN_IRLED1_ANODE		PINA
#define PIN_NUMBER_IRLED1_ANODE	3

#define DDR_IRLED2_ANODE		DDRA
#define PORT_IRLED2_ANODE		PORTA
#define PIN_IRLED2_ANODE		PINA
#define PIN_NUMBER_IRLED2_ANODE	4

#define DDR_IRLED3_ANODE		DDRA
#define PORT_IRLED3_ANODE		PORTA
#define PIN_IRLED3_ANODE		PINA
#define PIN_NUMBER_IRLED3_ANODE	1

#endif /* DEFINES_H_ */